require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4.4

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'

Documentation:
  Enabled: false
