inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec_rails

AllCops:
  UseCache: false
  TargetRubyVersion: 3.4.2
  NewCops: disable
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'bin/*'
    - 'app/pdfs/*.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
    - 'config/environments/*.rb'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 250

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
