version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a01677
    ports:
      - "3307:3306"
  insitu:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/opt/insitu/current
      - bundle:/bundle
    ports:
      - "3000:3000"
      - "1234:1234"
    depends_on:
      - db
volumes:
  mysql-data:
    driver: local
  bundle:
    driver: local
